export * from './catCard/CatCard'
export * from './featured/Featured'
export * from  './footer/Footer'
export * from './gigCard/GigCard'
export * from './navbar/Navbar'
export * from './projectCard/ProjectCard'
export * from './slide/Slide'
export * from './trustedBy/TrustedBy'
